name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

            #上传编译好的文件。
    - name: Upload_files
      uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: ${{env.SOLUTION_FILE_PATH}}
